# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AppSettingDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppSettingDialog(object):
    def setupUi(self, AppSettingDialog):
        AppSettingDialog.setObjectName("AppSettingDialog")
        AppSettingDialog.resize(726, 380)
        self.VerticalLayout = QtWidgets.QVBoxLayout(AppSettingDialog)
        self.VerticalLayout.setContentsMargins(5, 5, 5, 10)
        self.VerticalLayout.setSpacing(5)
        self.VerticalLayout.setObjectName("VerticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.appSettingTreeWidget = QtWidgets.QTreeWidget(AppSettingDialog)
        self.appSettingTreeWidget.setObjectName("appSettingTreeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.appSettingTreeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.appSettingTreeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.appSettingTreeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.appSettingTreeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.appSettingTreeWidget)
        self.appSettingTreeWidget.header().setVisible(True)
        self.horizontalLayout.addWidget(self.appSettingTreeWidget)
        self.appSettingGroupBox = QtWidgets.QGroupBox(AppSettingDialog)
        self.appSettingGroupBox.setTitle("")
        self.appSettingGroupBox.setObjectName("appSettingGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.appSettingGroupBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.appSettingStackedWidget = QtWidgets.QStackedWidget(self.appSettingGroupBox)
        self.appSettingStackedWidget.setObjectName("appSettingStackedWidget")
        self.workingSpaceSettingPage = QtWidgets.QWidget()
        self.workingSpaceSettingPage.setObjectName("workingSpaceSettingPage")
        self.gridLayout = QtWidgets.QGridLayout(self.workingSpaceSettingPage)
        self.gridLayout.setObjectName("gridLayout")
        self.selectWorkingDirLineEdit = QtWidgets.QLineEdit(self.workingSpaceSettingPage)
        self.selectWorkingDirLineEdit.setObjectName("selectWorkingDirLineEdit")
        self.gridLayout.addWidget(self.selectWorkingDirLineEdit, 0, 1, 1, 1)
        self.selectWorkingDirPushButton = QtWidgets.QPushButton(self.workingSpaceSettingPage)
        self.selectWorkingDirPushButton.setText("")
        self.selectWorkingDirPushButton.setObjectName("selectWorkingDirPushButton")
        self.gridLayout.addWidget(self.selectWorkingDirPushButton, 0, 2, 1, 1)
        self.selectWorkingDirLabel = QtWidgets.QLabel(self.workingSpaceSettingPage)
        self.selectWorkingDirLabel.setObjectName("selectWorkingDirLabel")
        self.gridLayout.addWidget(self.selectWorkingDirLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.appSettingStackedWidget.addWidget(self.workingSpaceSettingPage)
        self.mlModelLibPage = QtWidgets.QWidget()
        self.mlModelLibPage.setObjectName("mlModelLibPage")
        self.mlModelLibPageGridLayout = QtWidgets.QGridLayout(self.mlModelLibPage)
        self.mlModelLibPageGridLayout.setObjectName("mlModelLibPageGridLayout")
        self.paramsFileDirLineEdit = QtWidgets.QLineEdit(self.mlModelLibPage)
        self.paramsFileDirLineEdit.setEnabled(False)
        self.paramsFileDirLineEdit.setObjectName("paramsFileDirLineEdit")
        self.mlModelLibPageGridLayout.addWidget(self.paramsFileDirLineEdit, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mlModelLibPageGridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.paramsFileDirLabel = QtWidgets.QLabel(self.mlModelLibPage)
        self.paramsFileDirLabel.setObjectName("paramsFileDirLabel")
        self.mlModelLibPageGridLayout.addWidget(self.paramsFileDirLabel, 0, 0, 1, 1)
        self.appSettingStackedWidget.addWidget(self.mlModelLibPage)
        self.cURLSettingPage = QtWidgets.QWidget()
        self.cURLSettingPage.setObjectName("cURLSettingPage")
        self.cURLSettingGridLayout = QtWidgets.QGridLayout(self.cURLSettingPage)
        self.cURLSettingGridLayout.setObjectName("cURLSettingGridLayout")
        self.cURLBinDirLabel = QtWidgets.QLabel(self.cURLSettingPage)
        self.cURLBinDirLabel.setObjectName("cURLBinDirLabel")
        self.cURLSettingGridLayout.addWidget(self.cURLBinDirLabel, 0, 0, 1, 1)
        self.cURLBinDirLineEdit = QtWidgets.QLineEdit(self.cURLSettingPage)
        self.cURLBinDirLineEdit.setEnabled(False)
        self.cURLBinDirLineEdit.setObjectName("cURLBinDirLineEdit")
        self.cURLSettingGridLayout.addWidget(self.cURLBinDirLineEdit, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cURLSettingGridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.appSettingStackedWidget.addWidget(self.cURLSettingPage)
        self.mySQLSettingPage = QtWidgets.QWidget()
        self.mySQLSettingPage.setObjectName("mySQLSettingPage")
        self.mySQLSettingGridLayout = QtWidgets.QGridLayout(self.mySQLSettingPage)
        self.mySQLSettingGridLayout.setObjectName("mySQLSettingGridLayout")
        self.mySQLHostLineEdit = QtWidgets.QLineEdit(self.mySQLSettingPage)
        self.mySQLHostLineEdit.setObjectName("mySQLHostLineEdit")
        self.mySQLSettingGridLayout.addWidget(self.mySQLHostLineEdit, 0, 1, 1, 1)
        self.mySQLHostLabel = QtWidgets.QLabel(self.mySQLSettingPage)
        self.mySQLHostLabel.setObjectName("mySQLHostLabel")
        self.mySQLSettingGridLayout.addWidget(self.mySQLHostLabel, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mySQLSettingGridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.mySQLPortLabel = QtWidgets.QLabel(self.mySQLSettingPage)
        self.mySQLPortLabel.setObjectName("mySQLPortLabel")
        self.mySQLSettingGridLayout.addWidget(self.mySQLPortLabel, 0, 3, 1, 1)
        self.mySQLPortLineEdit = QtWidgets.QLineEdit(self.mySQLSettingPage)
        self.mySQLPortLineEdit.setObjectName("mySQLPortLineEdit")
        self.mySQLSettingGridLayout.addWidget(self.mySQLPortLineEdit, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mySQLSettingGridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.appSettingStackedWidget.addWidget(self.mySQLSettingPage)
        self.geoserverSettingPage = QtWidgets.QWidget()
        self.geoserverSettingPage.setObjectName("geoserverSettingPage")
        self.geoserverSettingGridLayout = QtWidgets.QGridLayout(self.geoserverSettingPage)
        self.geoserverSettingGridLayout.setObjectName("geoserverSettingGridLayout")
        self.geoserverPortLineEdit = QtWidgets.QLineEdit(self.geoserverSettingPage)
        self.geoserverPortLineEdit.setObjectName("geoserverPortLineEdit")
        self.geoserverSettingGridLayout.addWidget(self.geoserverPortLineEdit, 0, 4, 1, 1)
        self.geoserverPortLabel = QtWidgets.QLabel(self.geoserverSettingPage)
        self.geoserverPortLabel.setObjectName("geoserverPortLabel")
        self.geoserverSettingGridLayout.addWidget(self.geoserverPortLabel, 0, 3, 1, 1)
        self.geoserverHostLabel = QtWidgets.QLabel(self.geoserverSettingPage)
        self.geoserverHostLabel.setObjectName("geoserverHostLabel")
        self.geoserverSettingGridLayout.addWidget(self.geoserverHostLabel, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.geoserverSettingGridLayout.addItem(spacerItem5, 1, 1, 1, 1)
        self.geoserverHostLineEdit = QtWidgets.QLineEdit(self.geoserverSettingPage)
        self.geoserverHostLineEdit.setObjectName("geoserverHostLineEdit")
        self.geoserverSettingGridLayout.addWidget(self.geoserverHostLineEdit, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.geoserverSettingGridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        self.appSettingStackedWidget.addWidget(self.geoserverSettingPage)
        self.horizontalLayout_3.addWidget(self.appSettingStackedWidget)
        self.horizontalLayout.addWidget(self.appSettingGroupBox)
        self.horizontalLayout.setStretch(1, 1)
        self.VerticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.okPushButton = QtWidgets.QPushButton(AppSettingDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout_2.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(AppSettingDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_2.addWidget(self.cancelPushButton)
        self.VerticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AppSettingDialog)
        self.appSettingStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AppSettingDialog)

    def retranslateUi(self, AppSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        AppSettingDialog.setWindowTitle(_translate("AppSettingDialog", "系统设置"))
        self.appSettingTreeWidget.headerItem().setText(0, _translate("AppSettingDialog", "设置选项"))
        __sortingEnabled = self.appSettingTreeWidget.isSortingEnabled()
        self.appSettingTreeWidget.setSortingEnabled(False)
        self.appSettingTreeWidget.topLevelItem(0).setText(0, _translate("AppSettingDialog", "工作空间"))
        self.appSettingTreeWidget.topLevelItem(1).setText(0, _translate("AppSettingDialog", "ML模型库"))
        self.appSettingTreeWidget.topLevelItem(2).setText(0, _translate("AppSettingDialog", "cURL程序"))
        self.appSettingTreeWidget.topLevelItem(3).setText(0, _translate("AppSettingDialog", "MySQL数据库"))
        self.appSettingTreeWidget.topLevelItem(4).setText(0, _translate("AppSettingDialog", "GeoServer"))
        self.appSettingTreeWidget.setSortingEnabled(__sortingEnabled)
        self.selectWorkingDirLabel.setText(_translate("AppSettingDialog", "默认工作路径："))
        self.paramsFileDirLabel.setText(_translate("AppSettingDialog", "参数文件路径："))
        self.cURLBinDirLabel.setText(_translate("AppSettingDialog", "cURL路径："))
        self.mySQLHostLabel.setText(_translate("AppSettingDialog", "Host："))
        self.mySQLPortLabel.setText(_translate("AppSettingDialog", "端口："))
        self.geoserverPortLabel.setText(_translate("AppSettingDialog", "端口："))
        self.geoserverHostLabel.setText(_translate("AppSettingDialog", "Host："))
        self.okPushButton.setText(_translate("AppSettingDialog", "确定"))
        self.cancelPushButton.setText(_translate("AppSettingDialog", "取消"))
